DROP TABLE IF EXISTS PUBLIC.AUTHOR;

CREATE TABLE PUBLIC.AUTHOR (
  ID          INTEGER      NOT NULL AUTO_INCREMENT,
  FIRST_NAME  VARCHAR(255) NOT NULL,
  SECOND_NAME VARCHAR(255) NOT NULL,
  CONSTRAINT AUTHOR_PRIMARY_KEY PRIMARY KEY (ID),
);

DROP TABLE IF EXISTS PUBLIC.BOOK;

CREATE TABLE PUBLIC.BOOK (
  ID         INTEGER      NOT NULL AUTO_INCREMENT,
  NAME       VARCHAR(255) NOT NULL,
  PRINT_YEAR INTEGER(4)   NOT NULL,
  AUTHOR_ID  INTEGER      NOT NULL,
  CONSTRAINT AUTHOR_FOREIGN_KEY FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID)
);
